"""Ledger item 82: the artefact must record why a fetch failed and what concealed text.

The 2026-08-05 pass recorded `{url, flags}` per page and nothing else. Two things
became unanswerable the moment it finished:

* Which four of the 201 URLs failed to re-fetch, and why. That run was the first time
  the network paths had ever executed against live hosts, so those four outcomes were
  the only live evidence the fetch layer has ever produced, and they were discarded.
* Which concealment technique fired `hidden_content`. Item 43 carries a rule,
  registered in advance, about whether `display:none` should move buckets. It cannot
  be applied to an artefact that does not say which technique matched.

OPERATOR RULING, 2026-08-06: record the matched technique as a FIXED ENUM LABEL plus a
fetch-failure reason. No content strings, no matched-text excerpts, no evidence
snippets. The hash-only principle otherwise stands.

This file proves three things: the fields were absent before, they are present now,
and no page-controlled text can reach either of them.
"""

from __future__ import annotations

import importlib.util
import re
import subprocess
import sys

from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]


def _load(name: str):  # type: ignore[no-untyped-def]
    """Load a module from analysis/, mirroring tests/test_delta_pass.py."""
    spec = importlib.util.spec_from_file_location(
        name, REPO / "analysis" / f"{name}.py")
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


run_delta_pass = _load("run_delta_pass")

# The commit before the item 82 instrumentation.
PRE_CHANGE = "f30b441"

SECRET = "CANARY-e3f1a9-do-not-leak-this-page-text"


# --- fail-before ---------------------------------------------------------------


def test_the_pre_change_writer_recorded_neither_field() -> None:
    """Structural control: the fields genuinely did not exist before this change."""
    old = subprocess.run(
        ["git", "show", f"{PRE_CHANGE}:analysis/run_delta_pass.py"],
        cwd=REPO, capture_output=True, text=True, check=True,
    ).stdout
    assert "fetch_failures" not in old
    assert "hidden_text_techniques" not in old
    assert "FETCH_FAILURE_REASONS" not in old
    # And the artefact it produced carries neither key.
    artefact = (REPO / "analysis" / "corpus" / "realpage" / "DELTA-PASS.json")
    if artefact.is_file():
        text = artefact.read_text(encoding="utf-8")
        assert "fetch_failures" not in text, (
            "the committed 2026-08-05 artefact should still lack the field; "
            "it must not be regenerated by this work"
        )


# --- pass-after: concealment attribution ---------------------------------------


@pytest.mark.parametrize(
    "style,expected",
    [
        ("display:none", "display:none"),
        ("DISPLAY: NONE", "display:none"),
        ("visibility:hidden", "visibility:hidden"),
        ("visibility:collapse", "visibility:hidden"),
        ("opacity:0", "opacity:0"),
        ("font-size:0", "font-size:0"),
        ("height:0;overflow:hidden", "zero-box-clipped"),
    ],
)
def test_a_planted_concealed_page_is_attributed_to_its_technique(
    style: str, expected: str
) -> None:
    html = f'<html><body><p style="{style}">{SECRET}</p></body></html>'
    attributed = run_delta_pass.hidden_text_techniques(html)
    assert attributed, f"nothing attributed for {style!r}"
    assert expected in {t for techniques in attributed.values() for t in techniques}


def test_a_style_block_rule_is_attributed_too() -> None:
    html = (
        "<html><head><style>.x { display:none }</style></head>"
        f'<body><p class="x">{SECRET}</p></body></html>'
    )
    attributed = run_delta_pass.hidden_text_techniques(html)
    assert "display:none" in {t for ts in attributed.values() for t in ts}


@pytest.mark.parametrize(
    "style",
    ["position:absolute;left:-10000px", "clip-path:inset(100%)", "text-indent:-9999px"],
)
def test_unflagged_techniques_are_not_attributed(style: str) -> None:
    """Bucket (b) techniques must stay out, or attribution contradicts the detector."""
    html = f'<html><body><p style="{style}">{SECRET}</p></body></html>'
    assert run_delta_pass.hidden_text_techniques(html) == {}


def test_visible_content_is_not_attributed() -> None:
    html = f"<html><body><p>{SECRET}</p></body></html>"
    assert run_delta_pass.hidden_text_techniques(html) == {}


def test_attribution_agrees_with_the_detector_on_what_counts_as_concealed() -> None:
    """Correspondence pin.

    `_technique_for` is a second reading of the same rule the detector applies in
    `_assess_declarations`. If they ever disagree, the artefact would attribute a
    technique the detector did not flag, or stay silent on one it did.
    """
    from skillwatch.detector import _Concealment, _assess_declarations, _parse_declarations

    blocks = [
        "display:none", "visibility:hidden", "opacity:0", "font-size:0",
        "height:0;overflow:hidden", "position:absolute;left:-10000px",
        "clip-path:inset(100%)", "color:red", "height:0", "left:-10000px",
    ]
    for block in blocks:
        declarations, parsed = _parse_declarations(block)
        detector_says = _assess_declarations(declarations, parsed) is _Concealment.CONCEALED
        ours_says = run_delta_pass._technique_for(declarations, parsed) is not None
        assert detector_says == ours_says, f"disagreement on {block!r}"


# --- pass-after: fetch failure reasons -----------------------------------------


@pytest.mark.parametrize(
    "message,expected",
    [
        ("HTTPSConnectionPool: Read timed out.", "timeout"),
        ("getaddrinfo failed", "dns_failure"),
        ("SSLError: certificate verify failed", "tls_error"),
        ("Blocked: resolves to a private address", "blocked_by_ssrf_policy"),
        ("HTTP 503 from origin", "http_error"),
        ("Connection refused", "connection_failed"),
        ("", "other"),
        (None, "other"),
    ],
)
def test_a_planted_fetch_failure_classifies_to_a_closed_label(
    message: str | None, expected: str
) -> None:
    assert run_delta_pass.classify_fetch_failure(message) == expected


def test_every_reason_is_a_member_of_the_closed_vocabulary() -> None:
    samples = [
        "Read timed out", "getaddrinfo", "SSLError", "blocked private", "HTTP 500",
        "connection refused", "wholly unrecognised gibberish", None, "",
    ]
    for sample in samples:
        assert run_delta_pass.classify_fetch_failure(sample) in run_delta_pass.FETCH_FAILURE_REASONS


# --- the ruling: no page content may reach the artefact ------------------------


def test_no_page_text_survives_classification() -> None:
    """A server-controlled message must not pass through as itself."""
    hostile = f"Read timed out while reading {SECRET}"
    label = run_delta_pass.classify_fetch_failure(hostile)
    assert SECRET not in label
    assert label in run_delta_pass.FETCH_FAILURE_REASONS


def test_no_page_text_survives_attribution() -> None:
    """Attribution returns hashes and technique labels, never the concealed text."""
    html = f'<html><body><p style="display:none">{SECRET}</p></body></html>'
    attributed = run_delta_pass.hidden_text_techniques(html)
    serialised = repr(attributed)
    assert SECRET not in serialised
    for key, techniques in attributed.items():
        assert len(key) == 16 and all(c in "0123456789abcdef" for c in key)
        for technique in techniques:
            assert technique in run_delta_pass.TECHNIQUE_LABELS


def test_the_artefact_writer_reads_only_closed_vocabulary_fields() -> None:
    """Source-level control over the writer, as the brief requires.

    The writer must not reference the raw `error` string or any content field when
    building the item 82 keys. It reads `failure_reason`, which is a label.
    """
    source = (REPO / "analysis" / "run_delta_pass.py").read_text(encoding="utf-8")
    # EVERY writer, not just the last one. The coverage-floor refusal added on
    # 2026-08-06 is a second `Path(args.out).write_text(`, and an earlier version of
    # this test sliced only the final block, so a new writer could have carried page
    # content past it unexamined. Checking one writer in a file with two is the same
    # scope defect this repository keeps logging.
    blocks = source.split("Path(args.out).write_text(")[1:]
    assert len(blocks) >= 2, "expected a refusal writer and a success writer"
    for i, block in enumerate(blocks):
        writer = block.split("indent=2", 1)[0]
        # Reading a field to DECIDE something is fine and necessary: the failure list
        # is built by filtering on f.get("error") and f.get("raw_html"). What must
        # never happen is a page-content field becoming a written value. So strip the
        # read-only filter expressions, then check what is left, which is what the
        # artefact actually carries.
        written = re.sub(r'f\.get\("[a-z_]+"\)', "<read>", writer)
        written = re.sub(r'f\["[a-z_]+"\]', "<read>", written)
        for forbidden in ("content_text", "raw_html", "evidence"):
            assert forbidden not in written, (
                f"artefact writer {i} writes {forbidden} rather than only reading it"
            )
        # `error` may be read as a filter; it must never be a written value or key.
        assert '"error":' not in written, f"artefact writer {i} records the raw error"
    combined = " ".join(blocks)
    assert "fetch_failures" in combined
    assert "by_hidden_technique" in combined
    assert "reportable" in combined


def test_the_failure_record_builder_never_copies_the_raw_message() -> None:
    source = (REPO / "analysis" / "run_delta_pass.py").read_text(encoding="utf-8")
    # Slice to the dedented closing bracket of the comprehension. Splitting on the
    # first "]" stops inside f["url"], which made an earlier version of this test
    # assert against three tokens and pass for the wrong reason.
    builder = source.split("fetch_failures = [", 1)[1].split("\n    ]", 1)[0]
    assert "failure_reason" in builder
    # The raw message may be READ to classify, but must not be copied into a record.
    assert '"reason": f["error"]' not in builder
    assert "f['error']" not in builder
